---
# run with ansible-playbook
- hosts: 127.0.0.1
  connection: local
  tasks:

    # ensure XDG_CONFIG_HOME exists
    - file: path="{{ ansible_env.XDG_CONFIG_HOME }}"
            state=directory

    # grab xdg conf dotfiles (files and dirs)
    - shell: "ls -d -1 {{ playbook_dir }}/dotfiles/xdg_config/*"
      register: xdg_dotfiles
      changed_when: False

    # symlink dotfiles in XDG_CONFIG_HOME
    - file: path="{{ ansible_env.XDG_CONFIG_HOME }}/{{ item | basename }}"
            src="{{ item }}"
            state=link
      with_items: "{{ xdg_dotfiles.stdout_lines }}"

    # symlink emacs init.el that reads config in XDG_CONFIG_HOME
    - file: path=~/.emacs.d/init.el
            src="{{ playbook_dir }}/dotfiles/emacs/init.el"
            state=link
