# https://thevaluable.dev/tmux-config-mouseless/

# Unbinds ----------------------------------------------------------------------
# are these still necessary?
unbind %
unbind '"'
unbind C-b

# Binds ------------------------------------------------------------------------
# fancy session switcher
unbind a
bind a display-popup -E -w 90% -h 90% "
  tmux ls -F '#{session_name}' \
  | grep -vxF \"$(tmux display-message -p '#S')\" \
  | fzf \
      --print0 \
      --prompt='session | ' \
      --preview-window='right:70%' \
      --preview 'tmux capture-pane -ep -t {}:1.1 | head -n 42 | bat --color=always --style=plain --paging=never' \
  | xargs -0 -r tmux switch-client -t
"

# vim-like movement
unbind h
bind h select-pane -L
unbind j
bind j select-pane -D
unbind k
bind k select-pane -U
unbind l
bind l select-pane -R

# clear screen
unbind i
bind i send-keys C-l

# set up a quake-style split
unbind q
bind q splitw -fvb -l10 -c "#{pane_current_path}"

# reload config
unbind r
bind r source-file "${XDG_CONFIG_HOME}/tmux/tmux.conf" \; display "Reloaded tmux.conf"

# splits
unbind s
bind s split-window -v -c "#{pane_current_path}"
unbind v
bind v split-window -h -c "#{pane_current_path}"

# toggle status bar visibility
unbind t
bind t set-option status

# convenient quick swaps
bind C-a switch-client -l
bind C-f select-window -t!

# Settings ---------------------------------------------------------------------
set -g detach-on-destroy off
# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
# Renumber windows to prevent gaps (e.g. 1 2 4 5)
set -g renumber-windows on
# make delay shorter
set -sg escape-time 0
# vim mode
set -g status-keys vi
set -g mode-keys vi
# move statusbar to top of screen
set-option -g status-position top
# enable clipboard
set -g set-clipboard on
set -g allow-passthrough on

# add clarity to current pane selection
set -g window-style 'bg=colour235'
set -g window-active-style 'bg=0'
set -g pane-border-style 'fg=colour240'
set -g pane-active-border-style 'fg=colour213'
set -g pane-border-lines heavy
set -g pane-border-status top
set -g pane-border-format '#{?pane_active, #{pane_current_path} >> #{pane_current_command} ,}'

# Colors -----------------------------------------------------------------------
set-option -sa terminal-features ',alacritty:RGB'
set-option -ga terminal-features ',alacritty:usstyle'
set-option -ga terminal-overrides ',alacritty:Tc'
set -g default-terminal 'xterm-256color'

# vim: ft=tmux
