# ------------------------------------------------------------------------------
# Bar
# ------------------------------------------------------------------------------
set -g @color-main "color213"
set -g @color-highlight "color39"
set -g @color-contrast "black"

set -g status-style "bg=#{@color-main},fg=#{@color-contrast}"

# Left Side  -------------------------------------------------------------------
set -g status-left "  "
set -ga status-left "#[reverse] #H #[noreverse]  "
set -ga status-left "#[fg=#{@color-highlight}]"
set -ga status-left "#[fg=#{@color-contrast},bg=#{@color-highlight}] #S "
set -ga status-left "#[bg=#{@color-highlight},fg=#{@color-main}]"
set -ga status-left "#[bg=#{@color-main}]  "
set -g status-left-length 0

# Right side -------------------------------------------------------------------
set -g status-right "#[fg=#{@color-highlight}]#[fg=#{@color-contrast},bg=#{@color-highlight}] %a %Y-%m-%d#[bg=#{@color-highlight},fg=#{@color-main}] #[bg=#{@color-main}] "

# Windows ----------------------------------------------------------------------
set -g window-status-format "  #I #W  "
set -g window-status-current-format "#[reverse] #I #W #[noreverse]"
set -g window-status-separator " "

# vim: ft=tmux
