# ------------------------------------------------------------------------------
# Bar
# ------------------------------------------------------------------------------
set -g status-style "bg=colour213,fg=black"

# Left Side  -------------------------------------------------------------------
set -g status-left " #[reverse] #H #[noreverse] #[fg=color39]#[fg=black,bg=color39] #S #[bg=color39,fg=color213]#[bg=color213] "
set -g status-left-length 0

# Right side -------------------------------------------------------------------
set -g status-right "%a %Y-%m-%d  "

# Windows ----------------------------------------------------------------------
set -g window-status-format "  #I #W  "
set -g window-status-current-format "#[reverse]  #I #W  #[noreverse]"
set -g window-status-separator " "

# vim: ft=tmux
