# Plugins ----------------------------------------------------------------------
set-environment -g TMUX_PLUGIN_MANAGER_PATH "${XDG_DATA_HOME}/tmux"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'erikw/tmux-powerline'

# must be last line in the config!
run "${XDG_DATA_HOME}/tmux/tpm/tpm"

# vim: ft=tmux
