[[ -f "$XDG_CONFIG_HOME"/x11/xresources ]] && xrdb -merge -I$HOME "$XDG_CONFIG_HOME"/x11/xresources

xrandr --output HDMI-0 --mode 2560x1440 --rate 120
xrandr --output DVI-D-0 --mode 1920x1080 --rate 144

bspwm
